version: '3.3'

services:
  db:
    image: 'postgres:12'
    hostname: postgres
    container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'